### ISSUE TITLE
H function is undeterministic

### ISSUE THREAD

**Issue by baptistecolin** [baptistecolin/itsuku#3]
Looks like the H function in `itsuku.py` does not behave deterministically, which is not what we want ...

The following test fails : 
```python3
sha = sha512()
sha_input = int_to_4bytes(123)
sha.update(sha_input)
assert sha.digest[:10] == H(10, sha_input)
```

The comparison in the assertion fails because the two string are totally different. Moreover, if you run the test again, you will see that the right-hand term in the assertion is never the same. Which is why I'm calling this "undeterministic". Meanwhile, the left-hand term remains the same frome one test to another, which is what is expected. 

If you figure out what's wrong with our H function, please let us know !

**Comment by 14alarro** [comment]
The problem seems to be that the "digest" function returns the digest of ALL the data sent via the "update" function so far. Which means that in the following code : 
```
sha = sha512()
sha.update(b'a') 
a = sha.digest()
sha.update(b'a')
b = sha.digest()
```

`a` and `b` are not equals. However, `b` equals `c` with `c` defined as follow : 
```
sha2 = sha512()
sha2.update(b'aa')
c = sha2.digest()
```

So in order to get a more deterministic function, a new "sha512" object should be created in each function call. The following form could also be used : 
```
c  = sha512(b'aa').digest()
```

**Comment by baptistecolin** [comment]
Got it. However, seeing how H is defined in the original paper, it seems like the H function should be deterministic (as in : should not depend on previous inputs). So I guess the modifications should take place in the scripts rather than in the tests

**Comment by baptistecolin** [comment]
Okkk I thing it's ok now, see [this commit](https://github.com/baptistecolin/itsuku/commit/de4b892b4d170ef3e2e6d41b1d5d175b173fa148)
